name: .NET Build Serilog.Sinks.Mongodb.TimeSeries
on:
  push:
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - run: echo ${{matrix.os}}

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v3
        with:
         dotnet-version: '7.0.x'

      - name: Install dependencies
        run: dotnet restore

      - name: Build Serilog.Sinks.Mongodb.TimeSeries
        run: dotnet build --no-restore --configuration Release

      - name: Test Serilog.Sinks.Mongodb.TimeSeries
        run: dotnet test --no-build --configuration Release --logger GitHubActions
