name: Publish documentation
on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"
jobs:
  build:
    runs-on: windows-latest
    timeout-minutes: 15
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Install dependencies
        run: dotnet restore

      - name: Build Serilog.Sinks.Mongodb.TimeSeries
        run: dotnet build --no-restore --configuration Release

      - name: Test Serilog.Sinks.Mongodb.TimeSeries
        run: dotnet test --no-build --configuration Release --logger GitHubActions

      - name: Setup DocFX
        uses: crazy-max/ghaction-chocolatey@v3
        with:
          args: install docfx

      - name: DocFX Build
        working-directory: docs
        run: docfx docfx.json
        continue-on-error: false

      - name: Publish documentation
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.PAT }}
          publish_dir: docs/_site
          force_orphan: true
          cname: sinks-mongodb-timeseries.brammys.com
